# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, ament-copyright, ament-flake8, ament-pep257, common-interfaces, python3Packages, rclpy }:
buildRosPackage rec {
  pname = "ros-humble-anchor-pkg";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  buildInputs = [ python3Packages.black ];
  checkInputs = [ ament-copyright ament-flake8 ament-pep257 python3Packages.pytest ];
  propagatedBuildInputs = [ common-interfaces python3Packages.pyserial rclpy ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "AGPL-3.0-only" ];
  };
}
