# Default initial positions for ASTRA_Arm's ros2_control fake system

initial_positions:
  Axis_0_Joint: 0
  Axis_1_Joint: 0
  Axis_2_Joint: -1.6
  Axis_3_Joint: -1.6
  Gripper_Slider_Left: 0
  Wrist-EF_Roll_Joint: 0
  Wrist_Differential_Joint: 0