# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1
default_acceleration_scaling_factor: 1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Axis_0_Joint:
    has_velocity_limits: true
    max_velocity: 31.41593
    has_acceleration_limits: true
    max_acceleration: 0.5
  Axis_1_Joint:
    has_velocity_limits: true
    max_velocity: 31.41593
    has_acceleration_limits: true
    max_acceleration: 0.5
  Axis_2_Joint:
    has_velocity_limits: true
    max_velocity: 31.41593
    has_acceleration_limits: true
    max_acceleration: 0.5
  Axis_3_Joint:
    has_velocity_limits: true
    max_velocity: 31.41593
    has_acceleration_limits: true
    max_acceleration: 0.5
  Gripper_Slider_Left:
    has_velocity_limits: true
    max_velocity: 0.015
    has_acceleration_limits: true
    max_acceleration: 0.5
  Gripper_Slider_Right:
    has_velocity_limits: true
    max_velocity: 0.015
    has_acceleration_limits: true
    max_acceleration: 0.5
  Wrist_Differential_Joint:
    has_velocity_limits: true
    max_velocity: 31.41593
    has_acceleration_limits: true
    max_acceleration: 0.5
  Wrist-EF_Roll_Joint:
    has_velocity_limits: true
    max_velocity: 31.41593
    has_acceleration_limits: true
    max_acceleration: 0.5