# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    astra_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

astra_arm_controller:
  ros__parameters:
    joints:
    - Axis_0_Joint
    - Axis_1_Joint
    - Axis_2_Joint
    - Axis_3_Joint
    - Wrist_Differential_Joint
    - Wrist-EF_Roll_Joint
    command_interfaces:
    - position
    - velocity
    state_interfaces:
    - position
    - velocity
    allow_nonzero_velocity_at_trajectory_end: false
hand_controller:
  ros__parameters:
    joint: Gripper_Slider_Left