# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    astra_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints: 
        - Axis_0_Joint
        - Axis_1_Joint
        - Axis_2_Joint
        - Axis_3_Joint
        - Wrist_Differential_Joint
        command_interfaces: 
        - position
        state_interfaces: 
        - position
        allow_nonzero_velocity_at_trajectory_end: true

    hand_controller:
      type: position_controllers/GripperActionController
      ros__parameters:
        joint: 
        - Wrist-EF_Roll_Joint
        command_interfaces: 
        - position

astra_arm_controller:
  ros__parameters:
    joints: 
    - Axis_0_Joint
    - Axis_1_Joint
    - Axis_2_Joint
    - Axis_3_Joint
    - Wrist_Differential_Joint
    command_interfaces: 
    - position
    state_interfaces: 
    - position
    allow_nonzero_velocity_at_trajectory_end: true

hand_controller:
  ros__parameters:
    joint: Wrist-EF_Roll_Joint
    command_interfaces: 
    - position