# Automatically generated by: ros2nix --flake --distro humble
{
  nix-ros-overlay ? builtins.fetchTarball "https://github.com/lopsided98/nix-ros-overlay/archive/master.tar.gz",
  pkgs ? import nix-ros-overlay { },
  rosDistro ? "humble",
  extraPkgs ? { },
  extraPaths ? [ ],
  withPackages ? _: [ ],
  extraShellHook ? "",
}:
pkgs.mkShell {
  name = "ros2nix ${rosDistro} shell";
  packages = [
    (pkgs.rosPackages.${rosDistro}.buildEnv {
      wrapPrograms = false;
      paths =
        [
          pkgs.colcon
          pkgs.rosPackages.${rosDistro}.ros-core

          # Work around https://github.com/lopsided98/nix-ros-overlay/pull/624
          pkgs.rosPackages.${rosDistro}.ament-cmake-core
          pkgs.rosPackages.${rosDistro}.python-cmake-module
        ]
        ++ (
          with pkgs;
          with pkgs.rosPackages.${rosDistro};
          with extraPkgs;
          [
            # Dependencies from package.xml files
            ament-cmake
            ament-cmake-gtest
            ament-copyright
            ament-flake8
            ament-lint-auto
            ament-lint-common
            ament-pep257
            common-interfaces
            control-msgs
            control-toolbox
            controller-manager
            diff-drive-controller
            geometry-msgs
            geometry2
            gripper-controllers
            joint-state-broadcaster
            joint-state-publisher
            joint-state-publisher-gui
            joint-trajectory-controller
            joy
            launch-param-builder
            moveit-common
            moveit-configs-utils
            moveit-core
            moveit-kinematics
            moveit-msgs
            moveit-planners
            moveit-ros-move-group
            moveit-ros-planning-interface
            moveit-ros-visualization
            moveit-ros-warehouse
            moveit-setup-assistant
            moveit-simple-controller-manager
            pluginlib
            python3Packages.crccheck
            python3Packages.black
            python3Packages.numpy
            python3Packages.pygame
            python3Packages.pyserial
            python3Packages.pytest
            python3Packages.scipy
            rclcpp
            rclpy
            robot-state-publisher
            ros-testing
            ros2-control
            rosidl-default-generators
            rosidl-default-runtime
            rviz-common
            rviz-default-plugins
            rviz2
            sensor-msgs
            std-msgs
            std-srvs
            tf2-eigen
            tf2-ros
            trajectory-msgs
            xacro
          ]
        )
        ++ builtins.attrValues extraPkgs
        ++ extraPaths
        ++ withPackages (pkgs // pkgs.rosPackages.${rosDistro});
      }
    )
  ];
  shellHook = ''
    # Setup ROS 2 shell completion. Doing it in direnv is useless.
    if [[ ! $DIRENV_IN_ENVRC ]]; then
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete ros2)"
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete colcon)"
    fi
  '' + extraShellHook;
}
