# Controller state message to transmit the entire state of the controller
# This is depricated and currently no longer in use. It remains as a backup in case it's needed.

#Triggers
float64 lt
float64 rt

#Bumbers
bool lb
bool rb

#Menu/Pause buttons (plus/minus on the Gulikit)
bool plus
bool minus

#Left stick values
float64 ls_x
float64 ls_y

#Right stick values
float64 rs_x
float64 rs_y

#Buttons
bool a
bool b
bool x 
bool y

#D-pad
bool d_up
bool d_down
bool d_left
bool d_right

#Home button
bool home
