# Topic: /arm/feedback/faerie

# Voltage readings
float32 bat_voltage     # Current voltage of the battery
float32 voltage_12      # Current voltage of the 12V rail
float32 voltage_5       # Current voltage of the 5V rail

# SHT sensor data
float32 sht_temp        # Temperature in Celsius from the SHT sensor on FAERIE
float32 sht_humidity    # Humidity in percentage from the SHT sensor on FAERIE

# Lux sensor readings 
# (placeholders, these will eventually each associate with a specific color)
float32 lux_1           # Lux reading 1
float32 lux_2           # Lux reading 2
float32 lux_3           # Lux reading 3
float32 lux_4           # Lux reading 4
float32 lux_5           # Lux reading 5
float32 lux_6           # Lux reading 6
float32 lux_7           # Lux reading 7