# Topic: /arm/feedback/socket

# Axis 0 feedback
float32 axis0_angle    # Current joint angle in degrees
float32 axis0_temp     # Current motor temperature in Celsius
float32 axis0_voltage  # Current motor voltage in volts
float32 axis0_current  # Current motor amperage in milliamps

# Axis 1 feedback
float32 axis1_angle    # Current joint angle in degrees
float32 axis1_temp     # Current motor temperature in Celsius
float32 axis1_voltage  # Current motor voltage in volts
float32 axis1_current  # Current motor amperage in milliamps

# Axis 2 feedback
float32 axis2_angle    # Current joint angle in degrees
float32 axis2_temp     # Current motor temperature in Celsius
float32 axis2_voltage  # Current motor voltage in volts
float32 axis2_current  # Current motor amperage in milliamps

# Axis 3 feedback
float32 axis3_angle    # Current joint angle in degrees
float32 axis3_temp     # Current motor temperature in Celsius
float32 axis3_voltage  # Current motor voltage in volts
float32 axis3_current  # Current motor amperage in milliamps

# Voltage feedback
float32 bat_voltage    # Current voltage of the battery
float32 voltage_12     # Current voltage of the 12V rail
float32 voltage_5      # Current voltage of the 5V rail
float32 voltage_3      # Current voltage of the 3.3V rail