# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - astra_arm_controller
    - hand_controller

  astra_arm_controller:
    type: FollowJointTrajectory
    joints:
      - Axis_0_Joint
      - Axis_1_Joint
      - Axis_2_Joint
      - Axis_3_Joint
      - Wrist_Differential_Joint
      - Wrist-EF_Roll_Joint
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - Gripper_Slider_Left
    action_ns: gripper_cmd
    default: true