# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, ament-copyright, ament-flake8, ament-pep257, common-interfaces, python3Packages, rclpy, ros2-interfaces-pkg }:
buildRosPackage rec {
  pname = "ros-humble-bio-pkg";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  checkInputs = [ ament-copyright ament-flake8 ament-pep257 python3Packages.pytest ];
  propagatedBuildInputs = [ common-interfaces rclpy ros2-interfaces-pkg ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "AGPL-3.0-only" ];
  };
}
