# Automatically generated by: ros2nix --flake --distro humble
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ament-lint-common, common-interfaces, rclcpp }:
buildRosPackage rec {
  pname = "ros-humble-latency-tester";
  version = "1.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ common-interfaces rclcpp ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Tests latency in ASTRA's comms.";
    license = with lib.licenses; [ "AGPL-3.0-only" ];
  };
}
